openapi: 3.0.0
info:
  title: bdtime24.net API
  version: 1.0.0
  description: bdtime24.net is a leading news source in Bangladesh, dedicated to providing comprehensive and up-to-the-minute news coverage 24 hours a day. As a top-level news platform, bdtime24.net ensures that its readers are always informed about the latest developments across various domains, including politics, economy, culture, sports, and international affairs.
  termsOfService: https://bdtime24.net.github.io/
  contact:
    name: Zobaidul Kazi
    email: zobaidulkazi@gmail.com
    url: https://bdtime24.net/contacts
  license:
    name: Apache License, Version 2.0
    url: https://apache.com
servers:
- description: Development
  url: https://localhost:8000/api/v1
- description: Production
  url: https://bdtime24.net/api/v1/
tags:
- name: HealthChecks
  description: public Api Endpoints Health Checks
- name: Authentications
  description: public Api Endpoints And Authentication Purpose
- name: Dashboards
  description: public Api Endpoints Dashboards Purpose
- name: Articles
  description: public Api Endpoints Article Purpose
- name: Categories
  description: public Api Endpoints Category Purpose
- name: Comments
  description: Auth user created and update, delete this comment in this api..
- name: Tags
  description: News Tags Endpoints



paths:
  /health:
    get:
      description: Testing For Server Health
      tags:
      - HealthChecks
      responses:
        '200':
          description: it will return success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server is Up and Running

  /auth/signup:
    post:
      description: For Creating An Account For Authentication
      tags: [Authentications]
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: zobaidulkazi
                email:
                  type: string
                  format: email
                  example: zobaidulkazi@gmail.com
                password:
                  type: string
                  format: password
                  example: password123
              required:
              - username
              - email
              - password
      responses:
        '201':
          description: Successfully Created Account
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 201
                  message:
                    type: string
                    example: user created Successfully
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: iIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        example: /auth/signup
                      signin:
                        type: string
                        example: /auth/signin

        '400':
          $ref: '#/components/responses/400'

  /auth/signin:
    post:
      description: For Sign In With Email And Password || Phone Number and OTP
      tags: [Authentications]
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: zobaidulkazi@gmail.com
                password:
                  type: string
                  format: password
                  example: password123
              required:
              - email
              - password
      responses:
        '200':
          description: Logged in Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    type: string
                    example: Logged in Successfully
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: iIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        example: /auth/login

        '400':
          $ref: '#/components/responses/400'

  /auth/update: # update route
    post:
      description: For Update User Details
      tags: [Authentications]
      security:
      - bearerAuth: []
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: zobaidulkazi
                role:
                  type: string
                  example: admin
              required:
              - name
              - role
      responses:
        '200':
          description: User Details Updated Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    type: string
                    example: User Details Updated Successfully
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: iIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  links:

        '400':
          $ref: '#/components/responses/400'

  /auth/change-password: # # change-password
    post:
      description: For Change Password
      tags: [Authentications]
      security:
      - bearerAuth: []
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  format: password
                  example: password123
                newPassword:
                  type: string
                  format: password
                  example: password123
              required:
              - oldPassword
              - newPassword

      responses:
        '200':
          description: Password Changed Successfully
        '400':
          $ref: '#/components/responses/400'

  /auth/forget-password:
    post:
      description: For Forget Password
      tags: [Authentications]
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: zobaidulkazi@gmail.com
              required:
              - email
      responses:
        '200':
          description: Password Changed Successfully
        '400':
          $ref: '#/components/responses/400'


  /auth/logout:
    post:
      description: For Logout
      tags: [Authentications]
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Logged out Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    example: Logged out Successfully
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        example: /auth/logout
                      signin:
                        type: string
                        example: /auth/signin

        '400':
          $ref: '#/components/responses/400'


#$# Dashboard: Start::::

  /dashboards:
    get:
      description: Authenticated User Can Get Dashboards Access Only
      tags: [Dashboards]
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Dashboards Fetched Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    type: string
                    example: Dashboards Fetched Successfully
                  data:
                    type: object
                    properties:
                      dashboards:
                        type: array
                        items:
                          $ref: '#/components/schemas/Dashboard'
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        example: /dashboards

        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'

  /dashboards/analytics:
    get:
      description: Authenticated User Can Get Analytics Access Only
      tags: [Dashboards]
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Analytics Fetched Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    type: string
                    example: Analytics Fetched Successfully
                  data:
                    type: object
                    properties:
                      analytics:
                        type: array
                        items:
                          $ref: '#/components/schemas/Dashboard'



## Articles ##

  /articles:
    get:
      description: Articles Response Successfully,
      tags: [Articles]
      responses:
        '200':
          description: Articles Fetched Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    format: int32
                    example: 200
                  message:
                    type: string
                    example: Articles Fetched Successfully
                  data:
                    type: object
                    properties:
                      Articles:
                        type: array
                        items:
                          


## Components

## article/create##

  /article/create:
    post:
      description: Created a new Article at this auth user..
      tags: [Articles]
      responses:
        '200':
            description: Articles Created Successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    statusCode:
                      type: integer
                      format: int32
                      example: 200
                    message:
                      type: string
                      example: Successfully Created a new Article
                    data:
                      type: object
                      properties:
                        Articles:
                          type: array
                          items:


# article/:id

  /article/:id:
    get::
      description: Get a Article by id..
      tags: [Articles]
      responses:
        '200':
            description: Articles get Successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    statusCode:
                      type: integer
                      format: int32
                      example: 200
                    message:
                      type: string
                      example: Successfully get all Article
                    data:
                      type: object
                      properties:
                        Articles:
                          type: array
                          items:



  /article/update:
    put:
      description: Update Article at this auth user ID..
      tags: [Articles]
      responses:
        '200':
            description: Articles Update Successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    statusCode:
                      type: integer
                      format: int32
                      example: 200
                    message:
                      type: string
                      example: Successfully Update a new Article
                    data:
                      type: object
                      properties:
                        Articles:
                          type: array
                          items:


  /article/delete:
    delete:
      description: Delete  Article at this auth user ID....
      tags: [Articles]
      responses:
        '200':
            description: Articles Delete Successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    statusCode:
                      type: integer
                      format: int32
                      example: 200
                    message:
                      type: string
                      example: Successfully Delete Article
                    data:
                      type: object
                      properties:
                        Articles:
                          type: array
                          items:
  

components:
  schemas:
    Signup:
      type: object
      properties:
        name:
          type: string
          example: zobaidulkazi
        email:
          type: string
          format: email
          example: zobaidulkazi@gmail.com
        password:
          type: string
          format: password
          example: password123

    Signin:
      type: object
      properties:
        email:
          type: string
          format: email
          example: zobaidulkazi@gmail.com
        password:
          type: string
          format: password
          example: password123

    Dashboard:
      type: object
      properties:
        name:
          type: string
          example: zobaidulkazi
        email:
          type: string
          format: email
          example: zobaidulkazi@gmail.com
        avatar_url:
          type: string
          example: https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                format: int32
                example: 400
              error:
                type: string
                example: Bad request
              data:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: email
                    message:
                      type: string
                      example: Invalid email address

    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                format: int32
                example: 401
              error:
                type: string
                example: Unauthorized
              message:
                type: string
                example: Authentication token is missing or invalid

    "404":
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                format: int32
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: The requested resource was not found
